name: Bitcoin Regtest Cluster

services:
  bitcoin-node-01:
    image: public.ecr.aws/bitnami/bitcoin:${BITCOIN_HASH_TAG:-27.0.0}
    hostname: bitcoin-node-01
    container_name: bitcoin-node-01
    networks:
      - engram-net
      - bitcoin-net
    ports:
      - "18443:18443"       # RPC
      - "28332:28332"       # ZMQ Block (Tailored for Vigilante Monitor)
    environment:
      - BITCOIN_NETWORK=regtest
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER:-engram_admin}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD:-secure_password_123}
    volumes:
      - ./data_node1:/bitnami/bitcoin/data
    command:
      - -txindex=1
      - -zmqpubrawblock=tcp://0.0.0.0:28332
      - -zmqpubrawtx=tcp://0.0.0.0:28333
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -dbcache=100       
      - -maxmempool=50     
      - -maxconnections=10 
    deploy:
      resources:
        limits:
          memory: 512M     
        reservations:
          memory: 256M


  bitcoin-node-02:
    image: public.ecr.aws/bitnami/bitcoin:27.0.0
    hostname: bitcoin-node-02
    container_name: bitcoin-node-02
    networks:
      - engram-net
      - bitcoin-net
    ports:
      - "19443:18443"
      - "29332:28332"
    environment:
      - BITCOIN_NETWORK=regtest
      - BITCOIN_RPC_USER=${RPC_USER:-engram_admin}
      - BITCOIN_RPC_PASSWORD=${RPC_PASSWORD:-secure_password_123}
    volumes:
      - ./data_node2:/bitnami/bitcoin/data
    command:
      - -txindex=1
      - -zmqpubrawblock=tcp://0.0.0.0:28332
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -dbcache=100       
      - -maxmempool=50     
      - -maxconnections=10
    deploy:
      resources:
        limits:
          memory: 512M     
        reservations:
          memory: 256M


networks:
  engram-net:
    name: engram-net
    external: true
  bitcoin-net:
    name: bitcoin-net
    driver: bridge