


services:
  stratium-node:




  # Nhiệm vụ: Đọc data từ Engram và "đóng dấu" lên Bitcoin
  vigilante-submitter:
    image: babylonlabs/babylond:main
    hostname: vigilante-submitter
    container_name: vigilante-submitter
    volumes:
      - ./config:/home/babylon/config
    command: 
      - vigilante 
      - submitter 
      - --config 
      - /home/babylon/config/submitter.toml
    networks:
      - engram-net


  # Nhiệm vụ: Theo dõi Bitcoin và báo cáo về cho Engram App-chain
  vigilante-reporter:
    image: babylonlabs/babylond:main
    hostname: vigilante-reporter
    container_name: vigilante-reporter
    volumes:
      - ./config:/home/babylon/config
    command: 
      - vigilante 
      - reporter 
      - --config 
      - /home/babylon/config/reporter.toml
    networks:
      - engram-net


  checkpointing-monitor:
    image: babylonlabs/babylond:main
    hostname: checkpointing-monitor
    container_name: checkpointing-monitor
    volumes:
      - ./config/monitor.toml:/home/babylon/config.toml
    # Lệnh chạy monitor của Babylon
    command: ["vigilante", "monitor", "--config", "/home/babylon/config.toml"]
    depends_on:
      - btc-primary
      - vigilante-reporter
    networks:
      - engram-net


  celestia-light-node:
    image: ghcr.io/celestiaorg/celestia-node:v0.14.1
    container_name: celestia-light-node
    networks:
      - engram-net
    ports:
      - "26659:26658" # Cổng API để Engram đẩy Blob
    environment:
      - NODE_TYPE=light
      - P2P_NETWORK=private
    volumes:
      - ./celestia_light_data:/home/celestia
    depends_on:
      - celestia-bridge
    command: >
      sh -c "
      celestia light init --p2p.network private &&
      celestia light start --core.ip celestia-app --p2p.network private --rpc.addr 0.0.0.0 --rpc.port 26658
      "
    deploy:
      resources:
        limits:
          memory: 512M


networks:
  engram-net:
    name: engram-net
    external: true